### PR TITLE
Compatible with Python 3

### PR DESCRIPTION
**Pull request by paulRbr**

### CODE REVIEW

**Comment by paulRbr** [comment]
cc @brian-rickman

**Comment by brian-rickman** [comment]
Hi @paulRbr.  Thanks for contributing to our project.  I apologize for the confusing message from our bot.  It's an internal thing that really shouldn't be connected to this repo.

**Comment by paulRbr** [comment]
> Hi @paulRbr. Thanks for contributing to our project. I apologize for the confusing message from our bot. It's an internal thing that really shouldn't be connected to this repo.

Haha no problem :)

**Comment by paulRbr** [comment]
Thanks for the merge !

**Comment by brian-rickman** [comment]
Thanks for contributing.  Your commit should be on PyPi now as version 0.0.4.

**Pull request merged**
