### PR TITLE
Make redirects more SEO friendly (set canonical rel link, noindex for robots)

### PR DESCRIPTION
**Pull request by XhmikosR**
Adds canonical, title and robots tags

@zhimsel

### CODE REVIEW

**Comment by XhmikosR** [comment]
BTW personally I'd even remove the `body` content since it's moot AFAICT.

**Comment by zhimsel** [comment]
I no longer work for DataRobot, and thus cannot merge any PRs.

**Comment by dschaper** [comment]
@XhmikosR I've forked to our org repo.

**Comment by coliff** [comment]
> I no longer work for DataRobot, and thus cannot merge any PRs.

Is there someone else who can merge PRs? maybe @burkestar ?

**Review by coliff — APPROVED** [review]
LGTM!

**Review by burkestar — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
