### PR TITLE
Use relative paths for redirects

### LINKED ISSUE #17: Redirects don't work locally
When the HTML output files are accessed locally (file:// protocol), the redirects don't work.

This is because of the leading slash in the redirect target.

Tested in Firefox and Chrome.

### mkdocs.yml

```yml
use_directory_urls: false
plugins:
    - redirects:
        redirect_maps:
            'old.md': 'new.md'
```

### old.html

```html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Redirecting...</title>
    <link rel="canonical" href="/new.html">
    <meta name="robots" content="noindex">
    <script>var anchor = window.location.hash.substr(1); location.href = "/new.html" + (anchor ? "#" + anchor : "")</script>
    <meta http-equiv="refresh" content="0; url=/new.html">
</head>

<body>
    Redirecting...
</body>

</html>
```

### Solution

If I manually replace **/new.html** by **new.html**, everything works fine, both locally and on the web, and both in Chrome and Firefox.

### LINKED ISSUE #35: Compatibility with mkdocs-redirects
[mkdocs-redirects](https://github.com/datarobot/mkdocs-redirects) allows for creating redirect pages when a page's path changes. If `example.com/foo/` is moved to `example.com/bar/`, the plugin generates an HTML page with a script that updates the `location.href` to cause the redirect (like `set-default`). However, since it is not aware that `mike` will place the generated content one directory down, the new `href` will be `/bar/` instead of `latest/bar/`.

`mkdocs-redirects` does check [site_url](https://www.mkdocs.org/user-guide/configuration/#site_url) in `mkdocs.yml` to see if the site is hosted in a sub-directory. This means `mike` could write out an updated `mkdocs.yml` with the version appended to the value of `site_url` to specify the name of the sub-directory.

### PR DESCRIPTION
**Pull request by plannigan**
Changes the path assigned to `location.href` to be relative to old html page.

The PR adds pytest test cases to verify the produced paths.

You can also see the [output in action](https://plannigan.github.io/actions-playground/dev-redirects/). These are the [configured redirects](https://github.com/plannigan/actions-playground/blob/main/mkdocs.yml#L20).

Using relative paths:
Fixes #17 (Local file redirects)
Fixes jimporter/mike#35 (Site hosted in a sub-directory without depending on a static `site_url` from the `mkdocs` config)

### CODE REVIEW

**Comment by plannigan** [comment]
@burkestar @zhimsel Would it be possible to get a review of these changes?

**Comment by zhimsel** [comment]
I no longer have write access to the repo as I no longer work at DataRobot.

**Review by prcr — APPROVED** [review]
I ran into the same issue of mkdocs-redirects not being compatible with mike.

Right now I'm already using the solution from this pull request in production:

https://github.com/codacy/docs/commit/4ee1d2edc3d5a6f718849f7aaa896cd060d9e39e

Here are the resulting changes to the redirect pages:

https://github.com/codacy/docs/commit/fc03c3bb3567f67dc65e66909d37781b205135fe

And here's the an example URL that correctly redirects to the target page:

https://docs.codacy.com/v2.0.387-deprecated/hc/en-us/articles/207278449/

**Comment by prcr** [comment]
@burkestar, how can we work to have these changes merged into the original project?

**Comment by burkestar** [comment]
Thanks @plannigan for the contribution here, and @prcr for the reminder.

I'll get this released to PyPI today.  Needs a changelog update and possibly a few other tweaks to get it ready.  Sorry for the long delay!

**Comment by burkestar** [comment]
Released as [1.0.2](https://pypi.org/project/mkdocs-redirects/)

**Comment by prcr** [comment]
Thanks for the quick reply @burkestar! :+1: 

I began doing a full rollout of the new version of the plugin to production but came across an issue in the specific scenario of having a redirect target `index.md` (as I'm doing to redirect a few deleted pages to the documentation homepage). I proposed a simple fix on https://github.com/datarobot/mkdocs-redirects/pull/21.

**Pull request merged**
